import { Ionicons } from '@expo/vector-icons';
import { router, Stack, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';
import { Fonts, useTheme } from '@/lib/theme';

type Profile={user_id:string;display_name:string;handle?:string;avatar_url?:string;bio?:string};
type PublicCollection={id:string;title:string;description:string};
export default function FoodieProfile(){
 const {id}=useLocalSearchParams<{id:string}>(); const {theme}=useTheme(); const ins=useSafeAreaInsets();
 const [profile,setProfile]=useState<Profile|null>(null); const [lists,setLists]=useState<PublicCollection[]>([]); const [following,setFollowing]=useState(false); const [own,setOwn]=useState(false);
 const [counts,setCounts]=useState({followers:0,following:0});
 const load=useCallback(async()=>{const uid=String(id);const [{data:p},{data:c},{data:u},followers,followingCount]=await Promise.all([supabase.from('user_profiles').select('user_id,display_name,handle,avatar_url,bio').eq('user_id',uid).maybeSingle(),supabase.from('collections').select('id,title,description').eq('owner_id',uid).eq('visibility','public'),supabase.auth.getUser(),supabase.from('profile_follows').select('*',{count:'exact',head:true}).eq('followed_id',uid),supabase.from('profile_follows').select('*',{count:'exact',head:true}).eq('follower_id',uid)]);setProfile(p);setLists(c??[]);setOwn(u.user?.id===uid);setCounts({followers:followers.count??0,following:followingCount.count??0});if(u.user) setFollowing(!!(await supabase.from('profile_follows').select('followed_id').eq('follower_id',u.user.id).eq('followed_id',uid).maybeSingle()).data);},[id]);
 useFocusEffect(useCallback(()=>{load().catch(()=>{});},[load]));
 const follow=async()=>{const {data}=await supabase.auth.getUser();if(!data.user){router.push('/comunidad-acceso');return;}if(following)await supabase.from('profile_follows').delete().eq('follower_id',data.user.id).eq('followed_id',String(id));else await supabase.from('profile_follows').insert({follower_id:data.user.id,followed_id:String(id)});setFollowing(!following);};
 return <View style={[s.root,{backgroundColor:theme.bg,paddingTop:ins.top}]}><Stack.Screen options={{headerShown:false}}/><View style={s.nav}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="chevron-back" size={22} color={theme.text}/></TouchableOpacity></View><ScrollView contentContainerStyle={{paddingBottom:40}}>
 <View style={s.head}>{profile?.avatar_url?<Image source={{uri:profile.avatar_url}} style={s.avatar}/>:<View style={[s.avatar,{backgroundColor:theme.surface,alignItems:'center',justifyContent:'center'}]}><Ionicons name="person" size={30} color={theme.textMute}/></View>}<Text style={[s.name,{color:theme.text}]}>{profile?.display_name??'Foodie'}</Text>{profile?.handle&&<Text style={[s.handle,{color:theme.textSecondary}]}>@{profile.handle}</Text>}<Text style={[s.handle,{color:theme.textSecondary}]}>{counts.followers} seguidores · {counts.following} siguiendo</Text>{profile?.bio&&<Text style={[s.bio,{color:theme.textSecondary}]}>{profile.bio}</Text>}{!own&&<TouchableOpacity style={[s.follow,{backgroundColor:following?theme.surface:theme.text,borderColor:theme.border}]} onPress={follow}><Text style={{color:following?theme.text:theme.bg,fontWeight:'700'}}>{following?'Siguiendo':'Seguir'}</Text></TouchableOpacity>}</View>
 <Text style={[s.label,{color:theme.textSecondary}]}>COLECCIONES</Text>{lists.map(l=><TouchableOpacity key={l.id} style={[s.row,{borderColor:theme.border}]} onPress={()=>router.push({pathname:'/coleccion-publica/[id]',params:{id:l.id}})}><View style={{flex:1}}><Text style={[s.listName,{color:theme.text}]}>{l.title}</Text>{!!l.description&&<Text style={[s.desc,{color:theme.textSecondary}]}>{l.description}</Text>}</View><Ionicons name="chevron-forward" size={17} color={theme.textMute}/></TouchableOpacity>)}</ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,paddingHorizontal:20},nav:{height:50,justifyContent:'center'},head:{alignItems:'center',paddingVertical:20},avatar:{width:72,height:72,borderRadius:36},name:{fontFamily:Fonts.brand,fontSize:27,fontWeight:'900',marginTop:12},handle:{fontSize:13,marginTop:2},bio:{fontSize:14,lineHeight:20,textAlign:'center',marginTop:10,maxWidth:300},follow:{height:40,borderRadius:20,borderWidth:StyleSheet.hairlineWidth,paddingHorizontal:24,justifyContent:'center',marginTop:16},label:{fontSize:11,fontWeight:'700',letterSpacing:1.2,marginTop:18},row:{minHeight:70,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:'row',alignItems:'center'},listName:{fontSize:16,fontWeight:'700'},desc:{fontSize:12,marginTop:3}});
