import { Ionicons } from '@expo/vector-icons';
import { router, Stack, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ToggleSwitch } from '@/components/toggle-switch';
import { supabase } from '@/lib/supabase';
import { Fonts, useTheme } from '@/lib/theme';
export default function Privacy(){const {theme}=useTheme();const ins=useSafeAreaInsets();const [publicProfile,setPublic]=useState(false);useFocusEffect(useCallback(()=>{supabase.auth.getUser().then(({data})=>data.user&&supabase.from('user_profiles').select('visibility').eq('user_id',data.user.id).maybeSingle()).then((r:any)=>setPublic(r?.data?.visibility==='public')).catch(()=>{});},[]));const toggle=async(v:boolean)=>{setPublic(v);const {data}=await supabase.auth.getUser();if(data.user)await supabase.from('user_profiles').update({visibility:v?'public':'private'}).eq('user_id',data.user.id);};return <View style={[s.root,{backgroundColor:theme.bg,paddingTop:ins.top}]}><Stack.Screen options={{headerShown:false}}/><TouchableOpacity style={s.back} onPress={()=>router.back()}><Ionicons name="chevron-back" size={22} color={theme.text}/></TouchableOpacity><Text style={[s.title,{color:theme.text}]}>Privacidad</Text><View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><View style={s.row}><View style={{flex:1}}><Text style={[s.rowTitle,{color:theme.text}]}>Perfil de Foodie visible</Text><Text style={[s.sub,{color:theme.textSecondary}]}>Muestra tu nombre, presentación y colecciones que decidas publicar.</Text></View><ToggleSwitch value={publicProfile} onValueChange={toggle}/></View><View style={[s.note,{borderTopColor:theme.border}]}><Ionicons name="chatbubble-ellipses-outline" size={18} color={theme.accent}/><Text style={[s.noteText,{color:theme.textSecondary}]}>Tus reseñas publicadas permanecen visibles aunque ocultes tu perfil. Se mostrarán sin enlace a tus colecciones. Puedes editar cada reseña desde el Patio correspondiente.</Text></View></View></View>}
const s=StyleSheet.create({root:{flex:1,paddingHorizontal:20},back:{width:44,height:54,justifyContent:'center'},title:{fontFamily:Fonts.brand,fontSize:36,fontWeight:'900',letterSpacing:-1.2,marginTop:12},card:{marginTop:28,borderRadius:20,borderWidth:StyleSheet.hairlineWidth,overflow:'hidden'},row:{minHeight:90,padding:16,flexDirection:'row',alignItems:'center',gap:18},rowTitle:{fontSize:16,fontWeight:'700'},sub:{fontSize:12.5,lineHeight:18,marginTop:4},note:{padding:16,borderTopWidth:StyleSheet.hairlineWidth,flexDirection:'row',alignItems:'flex-start',gap:10},noteText:{flex:1,fontSize:12.5,lineHeight:18}});
